### ISSUE TITLE
"A helper named "v-get" could not be found", when Ember CP Validations specified as addon dependency

### ISSUE THREAD

**Issue by Sinled** [offirgolan/ember-cp-validations#334]
### Environment

- Ember Version:  2.7.1
- Ember CLI Version: 2.6.3
- Ember CP Validations Version: 2.9.4

### Steps to Reproduce
1. create addon `someAddon`
2. add Ember CP Validations as dependency (in addon templates v-get helper works fine)
3. add `someAddon` to application, 
4. try to use `v-get` helper in application templates,  you will get  
```Uncaught Error: Assertion Failed: A helper named "v-get" could not be found```

maybe i am doing something wrong?
because inside dummy application in addon, all works fine

**Comment by rwjblue** [comment]
Your addon must setup the registry for the consuming app.  You basically need to implement `setupPreprocessorRegistry` and call ember-cp-validations hook with your apps registry.

https://github.com/offirgolan/ember-cp-validations/blob/master/index.js#L12

**Comment by Sinled** [comment]
@rwjblue Thanks, 
```js
    setupPreprocessorRegistry(type, registry) {
        this.eachAddonInvoke('setupPreprocessorRegistry', [type, registry]);
    },
```

it seems this code fixed my problem.
But why `setupPreprocessorRegistry` does not call by default, like `treeFor`, or `included`?

**Comment by rwjblue** [comment]
Because when you add a preprocessor addon to a project (either app or addon) it is intended to only affect the thing that directly included it.

**Comment by Sinled** [comment]
@rwjblue 
this is strange, adding `setupPreprocessorRegistry` fixed problem with `v-get` in parent application,

but now when i try to run tests or dummy application in addon, build fails. I suppose it is because of duplicate call in `ember-cp-validation`. What is the best way to deal with this problem?

**Comment by rwjblue** [comment]
You can wrap the call in a guard. Something like `if (!this.isDevelopingAddon()) { /* each addon invoke ... */ }`.

**Comment by escobera** [comment]
@rwjblue is this still the proposed solution for this problem?

I'm running version 2.12 of ember and when I add
```js
    setupPreprocessorRegistry(type, registry) {
        this.eachAddonInvoke('setupPreprocessorRegistry', [type, registry]);
    },
```
to my addon the consuming app errors out on boot with:
```
app-boot.js:2 Uncaught TypeError: require(...).default.create is not a function
    at app-boot.js:2
```

**Comment by Sinled** [comment]
@escobera 
after updating to 2.12 i ended up with such solution:

```js
setupPreprocessorRegistry(type, registry) {
        if (!this.isDevelopingAddon()) {
            const cpValidationsAddon = this.addons.find(addon => addon.name === 'ember-cp-validations');
            if (cpValidationsAddon && cpValidationsAddon.setupPreprocessorRegistry) {
                cpValidationsAddon.setupPreprocessorRegistry(type, registry);
            }
        }
    }
```
