### ISSUE TITLE
owner.factoryFor is not a function When access validate() methon in Ember engine

### ISSUE THREAD

**Issue by Sandeeprao69** [offirgolan/ember-cp-validations#475]
### Environment

- Ember Version: 2.11
- Ember CLI Version:2.11
- Ember CP Validations Version: 3.2.3

**Comment by Sandeeprao69** [comment]
work fine with ember 2.12 and Ember-engine 0.5.0 .

**Comment by jgelens** [comment]
Hmm weird, I'm also getting this on 2.12.

**Comment by Sandeeprao69** [comment]
Hey This is unrelated to the above problem but Can anyone tell me how to use Ember Cp validation with normal Object in Ember controller.
User.create(
     Ember.getOwner(this).ownerInjection(),
     { username: 'John' }
    );
This does not work on Ember controller, ownerInjection is only available on Ember routes.

**Comment by offirgolan** [comment]
@Sandeeprao69 where exactly are you creating your model? Can you give me an actual code snippet?

**Comment by Sandeeprao69** [comment]
Hey 
**My Validation file**
`import { validator, buildValidations } from 'ember-cp-validations';

const guestValidation = buildValidations({
    'guestDetails.email': [
        validator('presence', true),
        validator('format', {
            type: 'email',
            message: 'Please enter a valid email address'
        })
    ],
    'guestDetails.firstName': [
        validator('presence', true),
    ],
    'guestDetails.lastName': [
        validator('presence', true),
    ],
    'guestDetails.dateOfBirth': [
        validator('presence', true),
    ],
    'guestDetails.phoneNumber': [
        validator('presence', true),
        validator('length', {
            min: 10,
            max: 10
        })
    ]
});

export default guestValidation`

**My Controller**

import Ember from 'ember';
import guestValidations from '../validators/add-guest-validations'
export default Ember.Controller.extend( {
validationObj:Ember.Object.extend(guestValidations);
guestDetails:validationObj:Ember.create(Ember.getOwner(this).ownerInjection(),{
name:'',
})

}
It gives me error.

**Comment by jherdman** [comment]
Confirmed. This is happening in Ember 2.8 LTS, my models are components.

**Comment by jherdman** [comment]
This appears to be missing in your package.json https://www.npmjs.com/package/ember-factory-for-polyfill

**Comment by rwjblue** [comment]
https://github.com/offirgolan/ember-cp-validations/pull/443 updated `ember-getowner-polyfill` which in turn depends on `ember-factory-for-polyfill`.

**Comment by jherdman** [comment]
@rwjblue are you suggesting that apps on Ember not supporting `owner.factoryFor` need the above polyfill, or that this addon needs it?

**Comment by rwjblue** [comment]
Sorry, I'm saying that this addon already specifies `ember-getowner-polyfill` which in turn depends on `ember-factory-for-polyfill`. I am surprised that you are having an issue, the factory for stuff _should_ just work...

Can you `npm ls ember-getowner-polyfill` just to confirm we have the required versions (1.2.0+ is required to pull in `ember-factory-for-polyfill`)?

**Comment by jherdman** [comment]
Interesting. Okay, so here's what I see as the output:

```
my-app@0.0.0
├─┬ ember-cp-validations@3.3.0
│ └── ember-getowner-polyfill@1.2.2
├── ember-getowner-polyfill@1.0.1
└─┬ ember-simple-auth@1.1.0
  └── ember-getowner-polyfill@1.0.0
```

So it looks like e-cp-validations is requiring the correct version.

The second branch point to v1.0.1 is surprising to me. Maybe it's my understanding of NPM, but it would suggest that it's a direct dependency of my app — which it's not, we don't have it in our package.json.

**Comment by jherdman** [comment]
A quick follow up. I've nombom'd my app, and now everything appears to be okay. Many thanks for everyone's help.
